# Generated by Django 3.1.3 on 2020-11-15 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(blank=True, null=True)),
                ('photo', models.BinaryField(blank=True, null=True)),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('login', models.TextField()),
                ('creationdate', models.DateTimeField(auto_now_add=True, db_column='creationDate', null=True)),
                ('lastlogin', models.DateTimeField(auto_now_add=True, db_column='lastLogin', null=True)),
                ('permissionlevel', models.IntegerField(blank=True, db_column='permissionLevel', default=1, null=True)),
            ],
            options={
                'unique_together': {('email', 'login')},
            },
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('likes', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('title', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_criador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GamimgTrack.user')),
            ],
        ),
        migrations.CreateModel(
            name='LikePostagens',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('postagem_like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GamimgTrack.postagem')),
                ('user_like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GamimgTrack.user')),
            ],
        ),
        migrations.CreateModel(
            name='ComentariosPostagens',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GamimgTrack.postagem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GamimgTrack.user')),
            ],
        ),
    ]
