# Generated by Django 3.1.1 on 2020-10-24 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(blank=True, null=True)),
                ('photo', models.BinaryField(blank=True, null=True)),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('login', models.TextField()),
                ('creationdate', models.DateTimeField(auto_now_add=True, db_column='creationDate', null=True)),
                ('lastlogin', models.DateTimeField(blank=True, db_column='lastLogin', null=True)),
                ('permissionlevel', models.IntegerField(blank=True, db_column='permissionLevel', default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('likes', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('title', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_criador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GamimgTrack.user')),
            ],
        ),
    ]
