# Generated by Django 2.2.16 on 2020-11-18 04:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(help_text='Requer 25 caracteres ou menos. Letras, números e caracteres especiais @/./+/-/_', max_length=25, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.@+-]+$'), 'Entre com um login válido.', 'Inválido')], verbose_name='Login')),
                ('nome', models.CharField(max_length=255, null=True, verbose_name='Nome completo')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='E-mail válido')),
                ('photo', models.BinaryField(blank=True, null=True)),
                ('password', models.CharField(max_length=128, unique_for_month=True, verbose_name='Senha')),
                ('last_login', models.DateTimeField(blank=True, db_column='lastLogin', null=True, verbose_name='Último login')),
                ('creationdate', models.DateTimeField(blank=True, db_column='creationDate', default=django.utils.timezone.now, null=True, verbose_name='Data de criação')),
                ('permissionlevel', models.IntegerField(blank=True, db_column='permissionLevel', default=1, null=True, verbose_name='Permissões: 1 = normal_user, 2 = ?, 3 = tutor, 4 = moderator, 5 = administrador')),
                ('is_staff', models.BooleanField(default=False, help_text='Define se é admin do site', verbose_name='Status de equipe')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superuser')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'unique_together': {('login', 'email')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('likes', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('user_criador', models.ForeignKey(on_delete=models.SET('Desconhecido'), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('likes', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('title', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_criador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LikePostagens',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('postagem_like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GamimgTrack.Postagem')),
                ('user_like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('relative_image', models.BinaryField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('save_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('name', 'description')},
            },
        ),
        migrations.CreateModel(
            name='ComentariosPostagens',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.TextField(default='')),
                ('postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GamimgTrack.Postagem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
