# Generated by Django 3.1.1 on 2020-11-06 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GamimgTrack', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('email', 'login')},
        ),
    ]
