# Generated by Django 3.1.3 on 2020-11-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamimgTrack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentariospostagens',
            name='comentario',
            field=models.TextField(default=''),
        ),
    ]
