# Generated by Django 3.1.1 on 2020-10-23 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamimgTrack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='creationdate',
            field=models.DateTimeField(auto_now_add=True, db_column='creationDate', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='permissionlevel',
            field=models.IntegerField(blank=True, db_column='permissionLevel', default=0, null=True),
        ),
    ]
