# Generated by Django 3.1.1 on 2020-10-24 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamimgTrack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
