# Generated by Django 3.1.3 on 2020-11-25 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GamimgTrack', '0002_auto_20201121_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentariosReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.TextField(default='')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GamimgTrack.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
