# Generated by Django 3.1.1 on 2020-10-23 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GamimgTrack', '0002_auto_20201022_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='permissionlevel',
            field=models.IntegerField(blank=True, db_column='permissionLevel', default=1, null=True),
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('likes', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_criador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GamimgTrack.user')),
            ],
        ),
    ]
