# Generated by Django 3.1.1 on 2020-10-24 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamimgTrack', '0002_auto_20201023_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='title',
            field=models.TextField(),
        ),
    ]
