# Generated by Django 3.1.3 on 2020-12-01 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GamimgTrack', '0003_comentariosreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConviteAmizade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quem_enviou', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enviou', to=settings.AUTH_USER_MODEL)),
                ('quem_recebeu_o_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recebeu', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('quem_enviou', 'quem_recebeu_o_pedido')},
            },
        ),
        migrations.CreateModel(
            name='Amizade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amigo', to=settings.AUTH_USER_MODEL)),
                ('amigo2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amigo2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('amigo', 'amigo2')},
            },
        ),
    ]
