# Generated by Django 3.1.1 on 2020-10-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamimgTrack', '0004_likepostagens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likepostagens',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
